-------------------------------------
------------EXERCISES DATA-----------
-------------------------------------
insert into exercises (exercise_name, exercise_detail) values ('RDLs', '5 sets of 10 reps');
insert into exercises (exercise_name, exercise_detail) values ('Bicep Curl', '3 sets of 15 reps');
insert into exercises (exercise_name, exercise_detail) values ('Sprints', 'Sprints to exhaustion for 30 second on 1 minute off');
insert into exercises (exercise_name, exercise_detail) values ('Back Extension', '3 sets of 15 reps');
insert into exercises (exercise_name, exercise_detail) values ('Chest Press', '5 sets of 10 reps');
insert into exercises (exercise_name, exercise_detail) values ('Calf Raises', '5 sets of 15 reps');
insert into exercises (exercise_name, exercise_detail) values ('Bulgarian Squats', '3 sets of 12 reps');
insert into exercises (exercise_name, exercise_detail) values ('Hip Abduction', '5 sets of 20 reps');
insert into exercises (exercise_name, exercise_detail) values ('Hammer Curls', '3 sets of 15 reps');
insert into exercises (exercise_name, exercise_detail) values ('Good Mornings', '4 sets of 20');
insert into exercises (exercise_name, exercise_detail) values ('Planks', 'Hold till exhuastion for 5 sets');
insert into exercises (exercise_name, exercise_detail) values ('Shoulder Press', '5 sets of 10 reps');
insert into exercises (exercise_name, exercise_detail) values ('Side Plank', 'Hold till exhuastion for 5 sets');
insert into exercises (exercise_name, exercise_detail) values ('Yoga', 'A full hot hatha class for 60 minutes');
insert into exercises (exercise_name, exercise_detail) values ('Pilates', 'Reformer mat class for 50 minutes');
insert into exercises (exercise_name, exercise_detail) values ('Barre Physique', 'Barre class for 60 minutes');
insert into exercises (exercise_name, exercise_detail) values ('Barbell Squats', '5 sets of 10 reps');
insert into exercises (exercise_name, exercise_detail) values ('Sumo Squat', '3 sets of 5 reps');
insert into exercises (exercise_name, exercise_detail) values ('Deadlift', '4 sets of 5 reps');
insert into exercises (exercise_name, exercise_detail) values ('Hip Thrust', '5 sets of 10 reps');
insert into exercises (exercise_name, exercise_detail) values ('Burpees', '10 reps of burpees with a 30 second rest in between sets');
insert into exercises (exercise_name, exercise_detail) values ('Lunges', 'Alternating lunges for 30 seconds on, 1 minute off, for 3 sets');
insert into exercises (exercise_name, exercise_detail) values ('Jump Squats', '20 jump squats with 30 seconds rest in between sets');
insert into exercises (exercise_name, exercise_detail) values ('Mountain Climbers', 'Mountain climbers for 1 minute on, 30 seconds off, for 3 sets');
insert into exercises (exercise_name, exercise_detail) values ('Plank', 'Hold a plank for 1 minute with 30 seconds rest in between sets');
insert into exercises (exercise_name, exercise_detail) values ('Push-Ups', '15 push-ups with a 30 second rest in between sets');
insert into exercises (exercise_name, exercise_detail) values ('Sit-Ups', '20 sit-ups with a 30 second rest in between sets');
insert into exercises (exercise_name, exercise_detail) values ('Squat Jumps', '10 squat jumps with a 30 second rest in between sets');
insert into exercises (exercise_name, exercise_detail) values ('Jump Rope', 'Jump rope for 1 minute with 30 seconds rest in between sets');
insert into exercises (exercise_name, exercise_detail) values ('Dips', '15 dips with 30 seconds rest in between sets');
insert into exercises (exercise_name, exercise_detail) values ('Box Jumps', '10 box jumps with 30 seconds rest in between sets');
insert into exercises (exercise_name, exercise_detail) values ('Bicycle Crunches', '30 seconds of bicycle crunches with 1 minute rest in between sets');
insert into exercises (exercise_name, exercise_detail) values ('Russian Twists', '20 Russian twists with 30 seconds rest in between sets');
insert into exercises (exercise_name, exercise_detail) values ('Lateral Raises', '12 lateral raises with 30 seconds rest in between sets');
insert into exercises (exercise_name, exercise_detail) values ('Tricep Pushdowns', '15 tricep pushdowns with 30 seconds rest in between sets');
insert into exercises (exercise_name, exercise_detail) values ('Bicep Curls', '12 bicep curls with 30 seconds rest in between sets');
insert into exercises (exercise_name, exercise_detail) values ('Deadlifts', '10 deadlifts with 30 seconds rest in between sets');
insert into exercises (exercise_name, exercise_detail) values ('Rowing Machine', '1 minute on the rowing machine with 30 seconds rest in between sets');
insert into exercises (exercise_name, exercise_detail) values ('Step-Ups', '15 step-ups on a bench with 30 seconds rest in between sets');
insert into exercises (exercise_name, exercise_detail) values ('Bent Over Rows', '12 bent over rows with 30 seconds rest in between sets');
insert into exercises (exercise_name, exercise_detail) values ('Reverse Flys', '15 reverse flys with 30 seconds rest in between sets');
insert into exercises (exercise_name, exercise_detail) values ('Calf Raises', '20 calf raises with 30 seconds rest in between sets');
insert into exercises (exercise_name, exercise_detail) values ('Lat Pulldowns', '12 lat pulldowns with 30 seconds rest in between sets');
insert into exercises (exercise_name, exercise_detail) values ('Shoulder Press', '10 shoulder presses with 30 seconds rest in between sets');