---------------------------------
------------MEALS DATA-----------
---------------------------------
insert into meals (meal_name) values ('Turkey Dinner');
insert into meals (meal_name) values ('Chicken Salad');
insert into meals (meal_name) values ('Apple');
insert into meals (meal_name) values ('Chicken Breast');
insert into meals (meal_name) values ('Egg Sandwich');
insert into meals (meal_name) values ('Pear');
insert into meals (meal_name) values ('Tuna Salad');
insert into meals (meal_name) values ('Tofu Noodles');
insert into meals (meal_name) values ('Grapes');
insert into meals (meal_name) values ('Squash Pasta');
insert into meals (meal_name) values ('Chicken Teriyaki');
insert into meals (meal_name) values ('Noodle Soup');
insert into meals (meal_name) values ('Overnight Oats');
insert into meals (meal_name) values ('Chia Seed Pudding');
insert into meals (meal_name) values ('Green Smoothie');
insert into meals (meal_name) values ('Chocolate Protein Shake');
insert into meals (meal_name) values ('Tuna Sandwich');
insert into meals (meal_name) values ('Turkey Sandwich');
insert into meals (meal_name) values ('Sushi');
insert into meals (meal_name) values ('Granola Yogurt');
insert into meals (meal_name) values ('Grilled Chicken with Quinoa and Broccoli');
insert into meals (meal_name) values ('Turkey and Avocado Lettuce Wraps');
insert into meals (meal_name) values ('Shrimp and Vegetable Stir-Fry');
insert into meals (meal_name) values ('Baked Salmon with Asparagus and Sweet Potato');
insert into meals (meal_name) values ('Veggie and Hummus Wrap');
insert into meals (meal_name) values ('Chickpea and Kale Salad');
insert into meals (meal_name) values ('Turkey and Zucchini Meatballs with Spaghetti Squash');
insert into meals (meal_name) values ('Grilled Vegetable Skewers with Tzatziki Sauce');
insert into meals (meal_name) values ('Veggie and Egg White Omelette');
insert into meals (meal_name) values ('Lentil and Brown Rice Bowl');
insert into meals (meal_name) values ('Baked Chicken Breast with Roasted Brussels Sprouts');
insert into meals (meal_name) values ('Turkey and Berry Salad');
insert into meals (meal_name) values ('Cauliflower Rice and Chicken Stir-Fry');
insert into meals (meal_name) values ('Grilled Tuna Steak with Mixed Greens Salad');
insert into meals (meal_name) values ('Avocado and Egg Toast');
insert into meals (meal_name) values ('Quinoa and Black Bean Salad');
insert into meals (meal_name) values ('Slow Cooker Chicken and Vegetable Soup');
insert into meals (meal_name) values ('Grilled Veggie and Turkey Burger');
insert into meals (meal_name) values ('Kale and Quinoa Power Salad');
insert into meals (meal_name) values ('Baked Sweet Potato and Black Bean Tacos');
insert into meals (meal_name) values ('Turkey and Veggie Stuffed Peppers');
insert into meals (meal_name) values ('Broccoli and Chicken Alfredo with Whole Wheat Pasta');
insert into meals (meal_name) values ('Grilled Shrimp and Mango Salad');
insert into meals (meal_name) values ('Turkey and Avocado BLT on Whole Grain Bread');
insert into meals (meal_name) values ('Zucchini and Carrot Noodle Bowl with Peanut Sauce');
insert into meals (meal_name) values ('Baked Cod with Tomatoes and Zucchini');
insert into meals (meal_name) values ('Quinoa and Roasted Vegetable Bowl');
insert into meals (meal_name) values ('Grilled Chicken and Pineapple Skewers');
insert into meals (meal_name) values ('Turkey and Hummus Wrap with Carrots and Cucumber');
insert into meals (meal_name) values ('Spaghetti Squash and Meatball Bowl');
insert into meals (meal_name) values ('Grilled Veggie and Halloumi Cheese Skewers');
insert into meals (meal_name) values ('Baked Salmon and Vegetable Packets');
insert into meals (meal_name) values ('Quinoa and Grilled Chicken Salad');
insert into meals (meal_name) values ('Slow Cooker Vegetable and Chickpea Curry');
insert into meals (meal_name) values ('Grilled Turkey and Vegetable Kebabs');
insert into meals (meal_name) values ('Avocado and Chicken Salad on Whole Grain Bread');
insert into meals (meal_name) values ('Roasted Cauliflower and Chickpea Bowl');
insert into meals (meal_name) values ('Grilled Shrimp and Veggie Skewers');
insert into meals (meal_name) values ('Baked Sweet Potato and Turkey Chili');
insert into meals (meal_name) values ('Turkey and Vegetable Stuffed Sweet Potato');
insert into meals (meal_name) values ('Grilled Chicken and Zucchini Noodle Bowl');
insert into meals (meal_name) values ('Quinoa and Grilled Veggie Bowl');
insert into meals (meal_name) values ('Slow Cooker Turkey and Veggie Stew');
insert into meals (meal_name) values ('Grilled Salmon and Asparagus Skewers');
insert into meals (meal_name) values ('Turkey and Veggie Wrap with Yogurt Dipping Sauce');