insert into meals_tracker (meal_name, meal_date, completion, user_id) values ('Turkey Dinner', 1674000400, false, 1);
insert into meals_tracker (meal_name, meal_date, completion, user_id) values ('Chicken Salad', 1674007400, false, 1);
insert into meals_tracker (meal_name, meal_date, completion, user_id) values ('Apple', 1674006600, true, 1);
insert into meals_tracker (meal_name, meal_date, completion, user_id) values ('Chicken Breast', 1674014000, false, 1);
insert into meals_tracker (meal_name, meal_date, completion, user_id) values ('Egg Sandwich', 1674020800, false, 1);
insert into meals_tracker (meal_name, meal_date, completion, user_id) values ('Pear', 1674027600, true, 1);
insert into meals_tracker (meal_name, meal_date, completion, user_id) values ('Tuna Salad', 1674033200, false, 1);
insert into meals_tracker (meal_name, meal_date, completion, user_id) values ('Tofu Noodles', 1674038800, false, 1);
insert into meals_tracker (meal_name, meal_date, completion, user_id) values ('Grapes', 1674044400, true, 1);
insert into meals_tracker (meal_name, meal_date, completion, user_id) values ('Squash Pasta', 1674050000, false, 1);
insert into meals_tracker (meal_name, meal_date, completion, user_id) values ('Chicken Teriyaki', 1674056800, false, 1);
insert into meals_tracker (meal_name, meal_date, completion, user_id) values ('Noodle Soup', 1674064000, false, 1);
insert into meals_tracker (meal_name, meal_date, completion, user_id) values ('Overnight Oats', 1674070400, false, 1);
insert into meals_tracker (meal_name, meal_date, completion, user_id) values ('Chia Seed Pudding', 1674076800, false, 1);
insert into meals_tracker (meal_name, meal_date, completion, user_id) values ('Green Smoothie', 1674083200, false, 1);
insert into meals_tracker (meal_name, meal_date, completion, user_id) values ('Chocolate Protein Shake', 1674089600, false, 1);
insert into meals_tracker (meal_name, meal_date, completion, user_id) values ('Tuna Sandwich', 1674092400, false, 1);
insert into meals_tracker (meal_name, meal_date, completion, user_id) values ('Turkey Sandwich', 1674107600, false, 1);
insert into meals_tracker (meal_name, meal_date, completion, user_id) values ('Sushi', 1674116000, false, 1);
insert into meals_tracker (meal_name, meal_date, completion, user_id) values ('Granola Yogurt', 1674123600, false, 1);
insert into meals_tracker (meal_name,meal_date, completion, user_id) values ('Grilled Chicken and Pineapple Skewers', 1677191600, false, 1);
insert into meals_tracker (meal_name,meal_date, completion, user_id) values ('Turkey and Hummus Wrap with Carrots and Cucumber', 1675936400, false, 1);
insert into meals_tracker (meal_name,meal_date, completion, user_id) values ('Spaghetti Squash and Meatball Bowl', 1674681200, false, 1);
insert into meals_tracker (meal_name,meal_date, completion, user_id) values ('Grilled Veggie and Halloumi Cheese Skewers', 1677478800, false, 1);
insert into meals_tracker (meal_name,meal_date, completion, user_id) values ('Baked Salmon and Vegetable Packets', 1675671600, false, 1);
insert into meals_tracker (meal_name,meal_date, completion, user_id) values ('Quinoa and Grilled Chicken Salad', 1676503600, false, 1);
insert into meals_tracker (meal_name,meal_date, completion, user_id) values ('Slow Cooker Vegetable and Chickpea Curry', 1677560400, false, 1);
insert into meals_tracker (meal_name,meal_date, completion, user_id) values ('Grilled Turkey and Vegetable Kebabs', 1675980000, false, 1);
insert into meals_tracker (meal_name,meal_date, completion, user_id) values ('Avocado and Chicken Salad on Whole Grain Bread', 1677998000, false, 1);
insert into meals_tracker (meal_name,meal_date, completion, user_id) values ('Roasted Cauliflower and Chicken Bake', 1676717200, false, 1);
insert into meals_tracker (meal_name,meal_date, completion, user_id) values ('Grilled Shrimp and Vegetable Skewers', 1677608000, false, 1);
insert into meals_tracker (meal_name,meal_date, completion, user_id) values ('Turkey and Veggie Stir-Fry', 1676369200, false, 1);
insert into meals_tracker (meal_name,meal_date, completion, user_id) values ('Zucchini and Chicken Noodle Soup', 1676369200, false, 1);
insert into meals_tracker (meal_name,meal_date, completion, user_id) values ('Baked Sweet Potato and Black Bean Bowl', 1677604800, false, 1);
insert into meals_tracker (meal_name,meal_date, completion, user_id) values ('Quinoa and Black Bean Salad', 1675662800, false, 1);
insert into meals_tracker (meal_name,meal_date, completion, user_id) values ('Grilled Vegetable and Tofu Skewers', 1676503600, false, 1);
insert into meals_tracker (meal_name,meal_date, completion, user_id) values ('Turkey and Berry Salad', 1674754800, false, 1);